# Copy this file to /tmp/mini-tmux-<uid>/keybinds.conf
# Location: /tmp/mini-tmux-<uid>/keybinds.conf
# Place in /tmp/mini-tmux-<uid>/keybinds.conf
# KEY_PREFIX KEY ACTION
KEY_PREFIX 1 detach_session
KEY_PREFIX 2 new_pane
KEY_PREFIX 3 next_pane