# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/latos/mini-tmux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/latos/mini-tmux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/latos/mini-tmux/CMakeFiles /Users/latos/mini-tmux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/latos/mini-tmux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mini-tmux

# Build rule for target.
mini-tmux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mini-tmux
.PHONY : mini-tmux

# fast build rule for target.
mini-tmux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/build
.PHONY : mini-tmux/fast

client.o: client.c.o
.PHONY : client.o

# target to build an object file
client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/client.c.o
.PHONY : client.c.o

client.i: client.c.i
.PHONY : client.i

# target to preprocess a source file
client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/client.c.i
.PHONY : client.c.i

client.s: client.c.s
.PHONY : client.s

# target to generate assembly for a file
client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/client.c.s
.PHONY : client.c.s

log.o: log.c.o
.PHONY : log.o

# target to build an object file
log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/log.c.o
.PHONY : log.c.o

log.i: log.c.i
.PHONY : log.i

# target to preprocess a source file
log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/log.c.i
.PHONY : log.c.i

log.s: log.c.s
.PHONY : log.s

# target to generate assembly for a file
log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/log.c.s
.PHONY : log.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/main.c.s
.PHONY : main.c.s

server.o: server.c.o
.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i
.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s
.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/server.c.s
.PHONY : server.c.s

spawn.o: spawn.c.o
.PHONY : spawn.o

# target to build an object file
spawn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/spawn.c.o
.PHONY : spawn.c.o

spawn.i: spawn.c.i
.PHONY : spawn.i

# target to preprocess a source file
spawn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/spawn.c.i
.PHONY : spawn.c.i

spawn.s: spawn.c.s
.PHONY : spawn.s

# target to generate assembly for a file
spawn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/spawn.c.s
.PHONY : spawn.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux.dir/build.make CMakeFiles/mini-tmux.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mini-tmux"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... spawn.o"
	@echo "... spawn.i"
	@echo "... spawn.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

