# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/latos/project/mini-tmux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/latos/project/mini-tmux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/latos/project/mini-tmux/CMakeFiles /home/latos/project/mini-tmux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/latos/project/mini-tmux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mini-tmux-0.3.0-amd64

# Build rule for target.
mini-tmux-0.3.0-amd64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mini-tmux-0.3.0-amd64
.PHONY : mini-tmux-0.3.0-amd64

# fast build rule for target.
mini-tmux-0.3.0-amd64/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/build
.PHONY : mini-tmux-0.3.0-amd64/fast

client.o: client.c.o
.PHONY : client.o

# target to build an object file
client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/client.c.o
.PHONY : client.c.o

client.i: client.c.i
.PHONY : client.i

# target to preprocess a source file
client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/client.c.i
.PHONY : client.c.i

client.s: client.c.s
.PHONY : client.s

# target to generate assembly for a file
client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/client.c.s
.PHONY : client.c.s

input.o: input.c.o
.PHONY : input.o

# target to build an object file
input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/input.c.o
.PHONY : input.c.o

input.i: input.c.i
.PHONY : input.i

# target to preprocess a source file
input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/input.c.i
.PHONY : input.c.i

input.s: input.c.s
.PHONY : input.s

# target to generate assembly for a file
input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/input.c.s
.PHONY : input.c.s

log.o: log.c.o
.PHONY : log.o

# target to build an object file
log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/log.c.o
.PHONY : log.c.o

log.i: log.c.i
.PHONY : log.i

# target to preprocess a source file
log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/log.c.i
.PHONY : log.c.i

log.s: log.c.s
.PHONY : log.s

# target to generate assembly for a file
log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/log.c.s
.PHONY : log.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/main.c.s
.PHONY : main.c.s

render.o: render.c.o
.PHONY : render.o

# target to build an object file
render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/render.c.o
.PHONY : render.c.o

render.i: render.c.i
.PHONY : render.i

# target to preprocess a source file
render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/render.c.i
.PHONY : render.c.i

render.s: render.c.s
.PHONY : render.s

# target to generate assembly for a file
render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/render.c.s
.PHONY : render.c.s

server.o: server.c.o
.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i
.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s
.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/server.c.s
.PHONY : server.c.s

spawn.o: spawn.c.o
.PHONY : spawn.o

# target to build an object file
spawn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/spawn.c.o
.PHONY : spawn.c.o

spawn.i: spawn.c.i
.PHONY : spawn.i

# target to preprocess a source file
spawn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/spawn.c.i
.PHONY : spawn.c.i

spawn.s: spawn.c.s
.PHONY : spawn.s

# target to generate assembly for a file
spawn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/spawn.c.s
.PHONY : spawn.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/util.c.s
.PHONY : util.c.s

vendor/vterm/encoding.o: vendor/vterm/encoding.c.o
.PHONY : vendor/vterm/encoding.o

# target to build an object file
vendor/vterm/encoding.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/encoding.c.o
.PHONY : vendor/vterm/encoding.c.o

vendor/vterm/encoding.i: vendor/vterm/encoding.c.i
.PHONY : vendor/vterm/encoding.i

# target to preprocess a source file
vendor/vterm/encoding.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/encoding.c.i
.PHONY : vendor/vterm/encoding.c.i

vendor/vterm/encoding.s: vendor/vterm/encoding.c.s
.PHONY : vendor/vterm/encoding.s

# target to generate assembly for a file
vendor/vterm/encoding.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/encoding.c.s
.PHONY : vendor/vterm/encoding.c.s

vendor/vterm/keyboard.o: vendor/vterm/keyboard.c.o
.PHONY : vendor/vterm/keyboard.o

# target to build an object file
vendor/vterm/keyboard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/keyboard.c.o
.PHONY : vendor/vterm/keyboard.c.o

vendor/vterm/keyboard.i: vendor/vterm/keyboard.c.i
.PHONY : vendor/vterm/keyboard.i

# target to preprocess a source file
vendor/vterm/keyboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/keyboard.c.i
.PHONY : vendor/vterm/keyboard.c.i

vendor/vterm/keyboard.s: vendor/vterm/keyboard.c.s
.PHONY : vendor/vterm/keyboard.s

# target to generate assembly for a file
vendor/vterm/keyboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/keyboard.c.s
.PHONY : vendor/vterm/keyboard.c.s

vendor/vterm/mouse.o: vendor/vterm/mouse.c.o
.PHONY : vendor/vterm/mouse.o

# target to build an object file
vendor/vterm/mouse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/mouse.c.o
.PHONY : vendor/vterm/mouse.c.o

vendor/vterm/mouse.i: vendor/vterm/mouse.c.i
.PHONY : vendor/vterm/mouse.i

# target to preprocess a source file
vendor/vterm/mouse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/mouse.c.i
.PHONY : vendor/vterm/mouse.c.i

vendor/vterm/mouse.s: vendor/vterm/mouse.c.s
.PHONY : vendor/vterm/mouse.s

# target to generate assembly for a file
vendor/vterm/mouse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/mouse.c.s
.PHONY : vendor/vterm/mouse.c.s

vendor/vterm/parser.o: vendor/vterm/parser.c.o
.PHONY : vendor/vterm/parser.o

# target to build an object file
vendor/vterm/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/parser.c.o
.PHONY : vendor/vterm/parser.c.o

vendor/vterm/parser.i: vendor/vterm/parser.c.i
.PHONY : vendor/vterm/parser.i

# target to preprocess a source file
vendor/vterm/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/parser.c.i
.PHONY : vendor/vterm/parser.c.i

vendor/vterm/parser.s: vendor/vterm/parser.c.s
.PHONY : vendor/vterm/parser.s

# target to generate assembly for a file
vendor/vterm/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/parser.c.s
.PHONY : vendor/vterm/parser.c.s

vendor/vterm/pen.o: vendor/vterm/pen.c.o
.PHONY : vendor/vterm/pen.o

# target to build an object file
vendor/vterm/pen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/pen.c.o
.PHONY : vendor/vterm/pen.c.o

vendor/vterm/pen.i: vendor/vterm/pen.c.i
.PHONY : vendor/vterm/pen.i

# target to preprocess a source file
vendor/vterm/pen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/pen.c.i
.PHONY : vendor/vterm/pen.c.i

vendor/vterm/pen.s: vendor/vterm/pen.c.s
.PHONY : vendor/vterm/pen.s

# target to generate assembly for a file
vendor/vterm/pen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/pen.c.s
.PHONY : vendor/vterm/pen.c.s

vendor/vterm/screen.o: vendor/vterm/screen.c.o
.PHONY : vendor/vterm/screen.o

# target to build an object file
vendor/vterm/screen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/screen.c.o
.PHONY : vendor/vterm/screen.c.o

vendor/vterm/screen.i: vendor/vterm/screen.c.i
.PHONY : vendor/vterm/screen.i

# target to preprocess a source file
vendor/vterm/screen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/screen.c.i
.PHONY : vendor/vterm/screen.c.i

vendor/vterm/screen.s: vendor/vterm/screen.c.s
.PHONY : vendor/vterm/screen.s

# target to generate assembly for a file
vendor/vterm/screen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/screen.c.s
.PHONY : vendor/vterm/screen.c.s

vendor/vterm/state.o: vendor/vterm/state.c.o
.PHONY : vendor/vterm/state.o

# target to build an object file
vendor/vterm/state.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/state.c.o
.PHONY : vendor/vterm/state.c.o

vendor/vterm/state.i: vendor/vterm/state.c.i
.PHONY : vendor/vterm/state.i

# target to preprocess a source file
vendor/vterm/state.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/state.c.i
.PHONY : vendor/vterm/state.c.i

vendor/vterm/state.s: vendor/vterm/state.c.s
.PHONY : vendor/vterm/state.s

# target to generate assembly for a file
vendor/vterm/state.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/state.c.s
.PHONY : vendor/vterm/state.c.s

vendor/vterm/unicode.o: vendor/vterm/unicode.c.o
.PHONY : vendor/vterm/unicode.o

# target to build an object file
vendor/vterm/unicode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/unicode.c.o
.PHONY : vendor/vterm/unicode.c.o

vendor/vterm/unicode.i: vendor/vterm/unicode.c.i
.PHONY : vendor/vterm/unicode.i

# target to preprocess a source file
vendor/vterm/unicode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/unicode.c.i
.PHONY : vendor/vterm/unicode.c.i

vendor/vterm/unicode.s: vendor/vterm/unicode.c.s
.PHONY : vendor/vterm/unicode.s

# target to generate assembly for a file
vendor/vterm/unicode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/unicode.c.s
.PHONY : vendor/vterm/unicode.c.s

vendor/vterm/vterm.o: vendor/vterm/vterm.c.o
.PHONY : vendor/vterm/vterm.o

# target to build an object file
vendor/vterm/vterm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/vterm.c.o
.PHONY : vendor/vterm/vterm.c.o

vendor/vterm/vterm.i: vendor/vterm/vterm.c.i
.PHONY : vendor/vterm/vterm.i

# target to preprocess a source file
vendor/vterm/vterm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/vterm.c.i
.PHONY : vendor/vterm/vterm.c.i

vendor/vterm/vterm.s: vendor/vterm/vterm.c.s
.PHONY : vendor/vterm/vterm.s

# target to generate assembly for a file
vendor/vterm/vterm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/vendor/vterm/vterm.c.s
.PHONY : vendor/vterm/vterm.c.s

window.o: window.c.o
.PHONY : window.o

# target to build an object file
window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/window.c.o
.PHONY : window.c.o

window.i: window.c.i
.PHONY : window.i

# target to preprocess a source file
window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/window.c.i
.PHONY : window.c.i

window.s: window.c.s
.PHONY : window.s

# target to generate assembly for a file
window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mini-tmux-0.3.0-amd64.dir/build.make CMakeFiles/mini-tmux-0.3.0-amd64.dir/window.c.s
.PHONY : window.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mini-tmux-0.3.0-amd64"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... render.o"
	@echo "... render.i"
	@echo "... render.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... spawn.o"
	@echo "... spawn.i"
	@echo "... spawn.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... vendor/vterm/encoding.o"
	@echo "... vendor/vterm/encoding.i"
	@echo "... vendor/vterm/encoding.s"
	@echo "... vendor/vterm/keyboard.o"
	@echo "... vendor/vterm/keyboard.i"
	@echo "... vendor/vterm/keyboard.s"
	@echo "... vendor/vterm/mouse.o"
	@echo "... vendor/vterm/mouse.i"
	@echo "... vendor/vterm/mouse.s"
	@echo "... vendor/vterm/parser.o"
	@echo "... vendor/vterm/parser.i"
	@echo "... vendor/vterm/parser.s"
	@echo "... vendor/vterm/pen.o"
	@echo "... vendor/vterm/pen.i"
	@echo "... vendor/vterm/pen.s"
	@echo "... vendor/vterm/screen.o"
	@echo "... vendor/vterm/screen.i"
	@echo "... vendor/vterm/screen.s"
	@echo "... vendor/vterm/state.o"
	@echo "... vendor/vterm/state.i"
	@echo "... vendor/vterm/state.s"
	@echo "... vendor/vterm/unicode.o"
	@echo "... vendor/vterm/unicode.i"
	@echo "... vendor/vterm/unicode.s"
	@echo "... vendor/vterm/vterm.o"
	@echo "... vendor/vterm/vterm.i"
	@echo "... vendor/vterm/vterm.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

