#pragma once
#include <stddef.h>
#define PROTOCOL_VERSION 0

/* Message types. */
enum msgtype {
  MSG_VERSION = 12,

  MSG_IDENTIFY_FLAGS = 100,
  MSG_IDENTIFY_TERM,
  MSG_IDENTIFY_TTYNAME,
  MSG_IDENTIFY_OLDCWD, /* unused */
  MSG_IDENTIFY_STDIN,
  MSG_IDENTIFY_ENVIRON,
  MSG_IDENTIFY_DONE,
  MSG_IDENTIFY_CLIENTPID,
  MSG_IDENTIFY_CWD,
  MSG_IDENTIFY_FEATURES,
  MSG_IDENTIFY_STDOUT,
  MSG_IDENTIFY_LONGFLAGS,
  MSG_IDENTIFY_TERMINFO,

  MSG_COMMAND = 200,
  MSG_DETACH,
  MSG_LIST_SESSIONS,
  MSG_DETACHKILL,
  MSG_EXIT,
  MSG_EXITED,
  MSG_EXITING,
  MSG_LOCK,
  MSG_READY,
  MSG_RESIZE,
  MSG_SHELL,
  MSG_SHUTDOWN,
  MSG_OLDSTDERR, /* unused */
  MSG_OLDSTDIN,  /* unused */
  MSG_OLDSTDOUT, /* unused */
  MSG_SUSPEND,
  MSG_UNLOCK,
  MSG_WAKEUP,
  MSG_EXEC,
  MSG_FLAGS,

  MSG_READ_OPEN = 300,
  MSG_READ,
  MSG_READ_DONE,
  MSG_WRITE_OPEN,
  MSG_WRITE,
  MSG_WRITE_READY,
  MSG_WRITE_CLOSE,
  MSG_READ_CANCEL,

  MSG_GRID_SAVE,
};

struct msg_header {
  enum msgtype type;
  size_t len;
};